---
# Each component identified by its path prefix has a list of owners
components:

  # Ownership applies recursively to any file in a directory
  source/linux/Foundational_Components/Kernel/Kernel_Drivers/Network: &linux_net_list
    - Siddharth-Vadapalli-at-TI
    - chintan013
    - danish-ti
  source/linux/Foundational_Components/Kernel/Kernel_Drivers/PCIe: *linux_net_list
  source/linux/Foundational_Components/Kernel/Kernel_Drivers/USB: *linux_net_list
  source/linux/Foundational_Components/PRU-ICSS*: *linux_net_list
  source/linux/Foundational_Components_PRU_Subsystem.rst: *linux_net_list

  source/android: &android_list
    - glaroque
    - makohoek
    - vishalmti
  source/devices/*/android: *android_list

  source/system: &mpu_list
    - jeevantelukula
    - jsuhaas22
    - sadik-smd
  source/buildroot: *mpu_list
  source/linux/Foundational_Components/Hypervisor: *mpu_list
  source/linux/Foundational_Components/Tools: *mpu_list
  source/linux/Foundational_Components/Virtualization: *mpu_list
  source/debian: *mpu_list
  source/devices/*/debian: *mpu_list

  source/devices/AM335x/linux: &sitara_legacy_list
    - jeevantelukula
    - jmenti
  source/devices/AM437x/linux: *sitara_legacy_list
  source/devices/AM65X/linux: *sitara_legacy_list

  source/devices/AM64X/linux: *mpu_list
  source/devices/AM62X/linux:
    - *mpu_list
    - DhruvaG2000

  source/devices/AM62AX/linux: *mpu_list

  source/devices/AM62PX/linux:
    - *mpu_list
    - AashvijShenai

  source/devices/AM62LX/linux:
    - *mpu_list
    - bryanbrattlof
    - r-vignesh

  source/linux/Overview:
    - *mpu_list
    - aniket-l

  source/linux/Release_Specific:
    - *mpu_list
    - aniket-l
    - praneethbajjuri
    - uditkumarti

  source/linux/Foundational_Components:
    - devarsht
    - praneethbajjuri
    - r-vignesh
    - uditkumarti

  source/linux/Foundational_Components/IPC:
    - 3V3RYONE
    - h-nagalla
    - jmenti

  source/linux/Foundational_Components/U-Boot:
    - bryanbrattlof
    - jmenti

  source/linux/Foundational_Components/Kernel:
    - devarsht
    - praneethbajjuri
    - r-vignesh
    - uditkumarti

  source/linux/Foundational_Components/Power_Management:
    - DhruvaG2000
    - vishalmti

  source/linux/Foundational_Components/Graphics:
    - DarrenEtheridge
    - StaticRocket
